config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  resources :categories, except: [:new, :show]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show, :destroy] do
    resources :messages, only: [:destroy]  
  end
  devise_for :users

  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
    end
    collection do
      get 'search_by_category'
    end
  
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  
  # Defines the root path route ("/")
  # root "posts#index"
  root 'homes#top'

  get '/debug/migrate', to: 'debug#migrate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :comment, presence: true, length: { maximum: 200 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: { maximum:140 }
end

app/models/post.rb
class Post < ApplicationRecord
 
    attachment :image
    belongs_to :user
    validates :user_id, presence: true
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    belongs_to :category
    
    validates :location, presence: true, length: { maximum: 15 }
    validates :text, presence: true, length: { maximum: 195 }
    validates :image, presence: true

    enum status: { published: 0, draft: 1 }
    
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy 
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries

  attachment :profile_image

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end  
end

app/controllers/debug_controller.rb
class DebugController < ApplicationController
    skip_before_action :authenticate_user!, only: [:migrate]
    def migrate
      Rails.application.load_tasks
      Rake::Task['db:migrate'].invoke
      render plain: "Migration completed"
    end
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    # 公開された投稿またはログインユーザーの投稿を取得
    @posts = Post.published
  
    # カテゴリーリストを取得
    @categories = Category.all
  
    # 投稿を最新順で取得
    @posts = @posts.order(created_at: :desc)
  
    # 検索キーワードによるフィルタリング
    if params[:search].present?
      @posts = @posts.where('location LIKE ?', "%#{params[:search]}%")
    end
  
    # カテゴリーによるフィルタリング
    if params[:category_id].present?
      @posts = @posts.where(category_id: params[:category_id])
    end
  
    # ページネーションを適用
    @posts = @posts.page(params[:page]).per(9)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(9).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end
 
  def confirm
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end

  def search_by_category
    if params[:category_id].present?
      @posts = Post.where(category_id: params[:category_id]).order(created_at: :desc)
    else
      @posts = Post.all.order(created_at: :desc)
    end
  
    @categories = Category.all # フォーム用
    render :index # 検索結果を投稿一覧ページに表示
  end

  
  
  
  private
  def post_params
    params.require(:post).permit(:user_id, :location, :address, :text, :image, :status, :category_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
   
  def index
    @users = User.page(params[:page]).per(5).reverse_order
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(8).reverse_order
    @published_posts = @user.posts.published.page(params[:page]).per(8).reverse_order
     # 下書き投稿は、自分のものだけ取得
    if @user == current_user
      @draft_posts = @user.posts.draft.page(params[:page]).per(8).reverse_order
    else
      @draft_posts = Post.none # 他のユーザーの下書きは取得しない
    end
    
    @following_users = @user.following_user
    @follower_users = @user.follower_user
   
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu| 
        @userEntry.each do |u| 
          if cu.room_id == u.room_id 
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
     end
    end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_user.page(params[:page]).per(3).reverse_order
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end
  
  def create
    
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="row mt-5">
<% users.each do |user| %>
<div class="one-post card mt-3">
  <%= link_to user_path(user) do %>
  <div class="d-flex align-items-center">
    <%= attachment_image_tag user, :profile_image, size: '80x80', fallback: "no_image.svg", class: "mt-3 profile-img" %>
    <p class="caption h4 mt-4 mr-2"><%= user.name %></p>
     <p class="caption h4 mt-4 mr-2"><%= "#{user.posts.count} 投稿" %></p>
  </div>
 
  <% end %>
</div>
<% end %>
</div>
<%= paginate users %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
<meta name="viewport" content="width=device-width,initial-scale=1">
<head>
  <meta charset="UTF-8">
  <title>プロフィール編集</title>
  <link rel="stylesheet" href="styles.css">
</head>

<div class="cover-user-edit">
  <div class="container-fluid d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">プロフィール編集</h1>
    </div>
    <div class="row mt-5">
      <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <label class="form-label">名前</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">画像</label><br>
        <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.svg", class: "mb-3 profile-img" %><br>
         <%= f.file_field :profile_image %>
      </div>
      <div class="form-group">
        <label class="form-label">プロフィール文</label>
        <%= f.text_area :profile, class: "form-control" %><br>
      </div>
      <%= f.submit '保存する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
<meta name="viewport" content="width=device-width,initial-scale=1">
  <div class="container-fluid d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロワー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
    <%= link_to '戻る', :back %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="cover-user-index">
<meta name="viewport" content="width=device-width,initial-scale=1">
  <div class="container-fluid d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
    <%= link_to '戻る', :back %>
  </div>
</div>

app/views/users/index.html.erb
<div class="cover-user-index">
<meta name="viewport" content="width=device-width,initial-scale=1">
  <div class="container-fluid d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">ユーザ一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<div class="cover-user-show">
<meta name="viewport" content="width=device-width,initial-scale=1">
  <div class="container-fluid d-flex flex-column align-items-center">
    <div class="row mt-5">
      <% if user_signed_in? && @user == current_user %>
        <h1 class="font-weight-normal">マイページ</h1>
      <% else %>
        <h1 class="font-weight-normal"><%= @user.name %>さんのページ</h1>
      <% end %>
    </div>

    <% if user_signed_in? && @user == current_user %>
      <p class="d-flex align-self-end">
        <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-secondary me-3" %>
        <%= link_to rooms_path do %>
         <%= image_tag "message-icon.png", alt: "メッセージ", class: "message-icon" %>
        <% end %>
     </p>
    <% end %>

    <% if current_user != @user %>
      <% if current_user.following?(@user) %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォロー外す', user_relationships_path(@user.id),  data: { turbo_method: :delete }, class: "btn btn-danger" %>
        </p>
      <% else %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォローする', user_relationships_path(@user.id),  data: { turbo_method: :post }, class:"btn btn-secondary" %>
        </p>
      <% end %>
    <% end %>

    <div class="d-flex justify-content-end mt-4 me-4">
      <% if @user != current_user %>
        <% if (current_user.following?(@user)) && (@user.following?(current_user)) %>
          <% if @isRoom == true %>
            <%= link_to "チャットへ", room_path(@roomId), class: "btn btn-primary" %>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "チャットを始める", class: "btn btn-primary user-show-chat" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="d-flex">
      <%= attachment_image_tag @user, :profile_image, size: '150x150', fallback: "no_image.svg", class: "mb-3 profile-img" %>
      <h4 class="ml-3 mb-3 card profile"><%= @user.profile %></h4>
    </div>

    <div class="d-flex">
      <%= link_to follows_user_path(@user) do %>
        <h6>フォロー<%= @following_users.count %></h6>
      <% end %>  
      <%= link_to followers_user_path(@user) do %>
        <h6>フォロワー<%= @follower_users.count %></h6>
      <% end %>
    </div>

    <div class="row mt-5 index-left w-100">
      <h2>投稿</h2>
      <% if @published_posts.any? %>
        <% @published_posts.each do |post| %>
          <div class="one-post col-sm-3 mb-3">
            <%= link_to post_path(post) do %>
              <%= attachment_image_tag post, :image, format: 'jpeg', size: '200x200' %>
              <p class="caption mb-0"><%= post.location %></p>
              <p class="caption"><%= "#{post.comments.count} コメント" %></p>
            <% end %>
          </div>
        <% end %>
        <%= paginate @published_posts %>
      <% else %>
        <p>公開済みの投稿はありません。</p>
      <% end %>

      <% if @user == current_user %> <!-- ログイン中のユーザーと表示中のユーザーが一致する場合のみ表示 -->
        <h2>下書き</h2>
        <% if @draft_posts.any? %>
          <% @draft_posts.each do |post| %>
            <div class="one-post col-sm-3 mb-3">
              <%= link_to edit_post_path(post) do %>
                <%= attachment_image_tag post, :image, format: 'jpeg', size: '200x200', class: 'img-fluid' %>
                <p class="caption mb-0"><%= post.location %></p>
              <% end %>
            </div>
          <% end %>
          <%= paginate @draft_posts %>
        <% else %>
          <p>下書きの投稿はありません。</p>
        <% end %>
      <% end %> <!-- 条件終了 -->
    </div>
  </div>
</div>