config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  resources :categories, except: [:new, :show]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show, :destroy] do
    resources :messages, only: [:destroy]  
  end
  devise_for :users

  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
    end
    collection do
      get 'search_by_category'
    end
  
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  
  # Defines the root path route ("/")
  # root "posts#index"
  root 'homes#top'

  get '/debug/migrate', to: 'debug#migrate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :comment, presence: true, length: { maximum: 200 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: { maximum:140 }
end

app/models/post.rb
class Post < ApplicationRecord
 
    attachment :image
    belongs_to :user
    validates :user_id, presence: true
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    belongs_to :category
    
    validates :location, presence: true, length: { maximum: 15 }
    validates :text, presence: true, length: { maximum: 195 }
    validates :image, presence: true

    enum status: { published: 0, draft: 1 }
    
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy 
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries

  attachment :profile_image

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end  
end

app/controllers/debug_controller.rb
class DebugController < ApplicationController
    skip_before_action :authenticate_user!, only: [:migrate]
    def migrate
      Rails.application.load_tasks
      Rake::Task['db:migrate'].invoke
      render plain: "Migration completed"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width,initial-scale=1">
<html>
  <head>
    <title>みのりつながる</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <% if user_signed_in? %>
      <header class="header">
        <div id="headerInner" class="header__inner">
          <!-- ロゴ部分 -->
          <div class="header__logo">
            <%= link_to root_path do %>
              <%= image_tag asset_path("top_background.png"), alt: "つながるみのり", class: "logo-image" %>
            <% end %>
          </div>

          <!-- ハンバーガーメニュー -->
          <div class="header__menu-btn" id="spMenuBtn">
            <span></span>
            <span></span>
            <span></span>
          </div>

          <!-- メニューバー -->
          <div class="header__menu">
            <ul class="menu__list">
              <li class="menu__item"><%= link_to "ユーザ一覧", users_path, class: "nav-link" %></li>
              <li class="menu__item"><%= link_to "投稿一覧", posts_path, class: "nav-link" %></li>
              <li class="menu__item"><%= link_to "投稿する", new_post_path, class: "nav-link" %></li>
              <li class="menu__item"><%= link_to "下書き一覧", confirm_posts_path, class: "nav-link" %></li>
              <li class="menu__item"><%= link_to "マイページ", user_path(current_user.id), class: "nav-link" %></li>
              <li class="menu__item">
                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
              </li>
              <li class="menu__item"><%= link_to rooms_path, class: "nav-link" do %>
                <%= image_tag asset_path("mail.png"), alt: "メッセージ", class: "mail-icon" %>
                <% end %>
                </li>
            </ul>
          </div>
        </div>
      </header>
    <% else %>
      <!-- ログインしていない場合のヘッダー -->
      <header class="header">
        <div class="header__inner">
          <div class="header__logo">
            <%= link_to root_path do %>
              <%= image_tag "top_background.png", alt: "つながるみのり", class: "logo-image" %>
            <% end %>
          </div>
          <nav class="header__menu">
            <ul class="menu__list">
              <li class="menu__item"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
              <li class="menu__item"><%= link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
            </ul>
          </nav>
        </div>
      </header>
    <% end %>

    <!-- メインコンテンツ -->
    <%= yield %>
  </body>
</html>